-- Berry Brown · initial schema · 27 Sep 2026
-- Applied to project ylrqmwfnelwqbychdpfb (Tokyo) as migration "init_berrybrown".
-- To move regions: create a new project, then run this file in its SQL editor
-- (or `npx supabase db push` after `npx supabase link`).
--
-- Orders, enquiries, upload log, the cake log, reviews. Two storage buckets.
-- The site reads published cakes and reviews with the publishable key.
-- Everything else is written by the Cloudflare Worker with the secret key.

-- ORDERS ---------------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  ref text not null unique check (ref ~ '^BB-\d{6}-[A-Z0-9]{4}$'),
  channel text not null check (channel in ('online', 'whatsapp')),
  status text not null default 'pending' check (status in ('pending', 'paid', 'confirmed', 'delivered', 'cancelled')),
  fulfilment text not null check (fulfilment in ('delivery', 'pickup')),
  date date not null,
  slot text not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  address text,
  notes text,
  lines jsonb not null,
  subtotal integer not null,
  delivery integer not null default 0,
  total integer not null,
  stripe_session_id text,
  stripe_payment_intent text,
  paid_at timestamptz
);
comment on table public.orders is 'Every order of the Six: Stripe (channel online) and WhatsApp. Status moves pending → paid/confirmed → delivered.';
comment on column public.orders.lines is 'Array of {productId,sizeId,flavourId,qty,message,product,size,flavour,unit}. Names are copied in so the row stays readable if the catalogue changes.';
create index orders_created_at_idx on public.orders (created_at desc);
create index orders_status_idx on public.orders (status);

-- ENQUIRIES ------------------------------------------------------------
create table public.enquiries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  kind text not null check (kind in ('custom', 'company')),
  about text check (about in ('box', 'workshop', 'table')),
  answers jsonb,
  from_price integer,
  photos text[] not null default '{}',
  message text not null,
  status text not null default 'new' check (status in ('new', 'replied', 'quoted', 'confirmed', 'closed'))
);
comment on table public.enquiries is 'Custom-cake form sends and company enquiries, saved the moment the customer opens WhatsApp.';
create index enquiries_created_at_idx on public.enquiries (created_at desc);

-- UPLOADS (inspiration photos; used for the per-IP rate limit) --------
create table public.uploads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  ip_hash text not null,
  path text not null unique,
  bytes integer not null,
  content_type text not null
);
create index uploads_ip_hash_created_at_idx on public.uploads (ip_hash, created_at desc);

-- CAKES (the log) ------------------------------------------------------
create table public.cakes (
  n integer generated by default as identity primary key,
  created_at timestamptz not null default now(),
  made_for text not null,
  flavour text not null,
  size text not null,
  photo_path text,
  published boolean not null default false,
  order_id uuid references public.orders (id) on delete set null
);
comment on table public.cakes is 'Every cake gets a number. Rows are created automatically when an order is paid; publish the ones with a photo to show them on the site.';
comment on column public.cakes.photo_path is 'Object path inside the public "cakes" storage bucket, e.g. 041.jpg';
create index cakes_published_n_idx on public.cakes (published, n desc);

-- REVIEWS --------------------------------------------------------------
create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  area text not null default '',
  text text not null,
  cake text not null default '',
  stars smallint not null default 5 check (stars between 1 and 5),
  published boolean not null default false
);
comment on table public.reviews is 'Customer reviews. Only published rows appear on the site. Get permission before publishing.';
create index reviews_published_created_at_idx on public.reviews (published, created_at desc);

-- ROW LEVEL SECURITY ---------------------------------------------------
alter table public.orders enable row level security;
alter table public.enquiries enable row level security;
alter table public.uploads enable row level security;
alter table public.cakes enable row level security;
alter table public.reviews enable row level security;

-- Private tables: the public roles get nothing at all.
revoke all on public.orders, public.enquiries, public.uploads from anon, authenticated;

-- Public tables: read-only, published rows only, and only the columns the site needs.
revoke all on public.cakes, public.reviews from anon, authenticated;
grant select (n, created_at, made_for, flavour, size, photo_path, published) on public.cakes to anon, authenticated;
grant select (id, created_at, name, area, text, cake, stars, published) on public.reviews to anon, authenticated;

create policy "published cakes are public" on public.cakes
  for select to anon, authenticated using (published);
create policy "published reviews are public" on public.reviews
  for select to anon, authenticated using (published);

-- EVERY PAID CAKE GETS A NUMBER ---------------------------------------
create or replace function public.log_cakes_for_order()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  line jsonb;
  i integer;
begin
  if new.status = 'paid' and (tg_op = 'INSERT' or old.status is distinct from 'paid') then
    if not exists (select 1 from public.cakes c where c.order_id = new.id) then
      for line in select * from jsonb_array_elements(new.lines) loop
        for i in 1..greatest(1, coalesce((line->>'qty')::int, 1)) loop
          insert into public.cakes (made_for, flavour, size, order_id)
          values ('for ' || new.customer_name, coalesce(line->>'product', ''), coalesce(line->>'size', ''), new.id);
        end loop;
      end loop;
    end if;
  end if;
  return new;
end;
$$;
revoke execute on function public.log_cakes_for_order() from public, anon, authenticated;

create trigger orders_log_cakes
  after insert or update of status on public.orders
  for each row execute function public.log_cakes_for_order();

-- STORAGE --------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('inspiration', 'inspiration', false, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/heic']),
  ('cakes', 'cakes', true, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;
